# Use official lightweight Python image
FROM python:3.9-slim

# Create working directory
WORKDIR /workspace

# Copy entrypoint script
COPY run.py /workspace/run.py

# Default command
CMD ["python", "/workspace/run.py"]
