# Use official lightweight Python image
FROM python:3.9-slim

# Create working directory
WORKDIR /runner

# Copy entrypoint script
COPY run.py /runner/run.py

# Default command
CMD ["python", "/runner/run.py"]
